language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
install:
  - npm install
os: osx
osx_image: xcode12
branches:
  only:
  - develop
script: node scripts/build.js && node ftp.js