language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
install:
  - npm install
os: osx
osx_image: xcode12
deploy:
  - provider: script
    script: npm run deploy
    on:
      branch: develop
  - provider: script
    script: echo "Master branch publish..."
    on:
      branch: master
