language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
env:
  - CI=false
install:
  - npm install
os: osx
osx_image: xcode12
branches:
  only:
    - develop
script: node scripts/build.js && node ftp.js
